apiVersion: apps/v1
kind: Deployment
metadata:
  name: novapay
  namespace: novapay
spec:
  replicas: 10

  selector:
    matchLabels:
      app: novapay

  template:
    metadata:
      labels:
        app: novapay

    spec:
      containers:
      - name: novapay
        image: nginx:latest
        
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limit:
            cpu: "1"
            memory: "1Gi"

        ports:
        - containerPort: 80
