apiVersion: apps/v1
kind: Deployment
metadata:
  name: novapay
  namespace: novapay
spec:
  replicas: 2

  selector:
    matchLabels:
      app: novapay

  template:
    metadata:
      labels:
        app: novapay

    spec:
      containers:
      - name: novapay
        image: 187478112406.dkr.ecr.us-east-1.amazonaws.com/novapay-app:2.0.0
        imagePullPolicy: Always        
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limit:
            cpu: "1"
            memory: "1Gi"

        ports:
        - containerPort: 80
        env:
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: novapay-db-secret
                key: username

          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: novapay-db-secret
                key: password

    valueFrom:
      secretKeyRef:
        name: novapay-db-secret
        key: password
