apiVersion: v1
kind: Namespace
metadata:
  name: kube-system

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::187478112406:role/novapay-alb-controller
