apiVersion: velero.io/v1
kind: Schedule

metadata:
  name: daily-backup
  namespace: velero

spec:
  schedule: "0 1 * * *"

  template:
    ttl: 720h0m0s

    includedNamespaces:
      - "*"

    snapshotVolumes: true
