apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule

metadata:
  name: novapay-alerts
  namespace: monitoring

spec:
  groups:
    - name: novapay.rules

      rules:
        - alert: HighCPUUsage

          expr: |
            sum(rate(container_cpu_usage_seconds_total[5m])) > 0.8

          for: 5m

          labels:
            severity: critical

          annotations:
            summary: High CPU Usage Detected
            description: NovaPay CPU utilization exceeds threshold.