apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: novapay-primary
  namespace: argocd

spec:
  description: NovaPay Primary Region Applications

  sourceRepos:
    - '*'

  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
