apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret

metadata:
  name: novapay-db-secret
  namespace: default

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore

  target:
    name: novapay-db-secret
    creationPolicy: Owner

  data:
    - secretKey: username
      remoteRef:
        key: database/novapay
        property: username

    - secretKey: password
      remoteRef:
        key: database/novapay
        property: password